# Generated by Django 3.2.17 on 2024-05-05 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_alter_flight_airline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='flight.location'),
        ),
    ]
