# Generated by Django 5.0.4 on 2024-05-05 02:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flight", "0003_remove_flight_flight_class_ticket"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flight",
            old_name="arrival_datetime",
            new_name="return_datetime",
        ),
    ]
