# Generated by Django 3.2.17 on 2024-05-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_alter_flight_arrival_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stepover',
            new_name='Stopover',
        ),
    ]
