# Generated by Django 3.2.17 on 2024-05-06 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_rename_stepover_stopover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopover',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stopovers', to='flight.flight'),
        ),
    ]
