# Generated by Django 5.0.4 on 2024-05-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flight", "0004_rename_arrival_datetime_flight_return_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="checked_bag_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
