# Generated by Django 5.0.4 on 2024-05-05 01:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("FirstName", models.CharField(max_length=255)),
                ("LastName", models.CharField(max_length=255)),
                ("MiddleName", models.CharField(blank=True, max_length=255, null=True)),
                ("EmailAddress", models.EmailField(max_length=255)),
                ("DateOfBirth", models.DateField()),
                ("PhoneNumber", models.CharField(max_length=255)),
                ("PassportNumber", models.CharField(max_length=255)),
                ("PassportCountry", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
